-- ============================================================
--  MÓDULO SAC — Serviço de Atendimento ao Cliente
--  Domínio: www.ecommerce.com.br
--  Execute este script no Oracle antes de rodar a aplicação.
-- ============================================================

-- Tabela de Clientes do SAC
CREATE TABLE sac_clientes (
    id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR2(100) NOT NULL,
    email     VARCHAR2(150) NOT NULL UNIQUE,
    cpf       VARCHAR2(14)  NOT NULL UNIQUE,
    telefone  VARCHAR2(20)
);

-- Tabela de Tickets de Atendimento
CREATE TABLE sac_tickets (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo            VARCHAR2(200)  NOT NULL,
    descricao         VARCHAR2(1000) NOT NULL,
    status            VARCHAR2(20)   DEFAULT 'ABERTO'   NOT NULL,
    prioridade        VARCHAR2(10)   DEFAULT 'MEDIA'    NOT NULL,
    cliente_id        NUMBER         NOT NULL,
    data_criacao      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    data_atualizacao  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT fk_ticket_cliente FOREIGN KEY (cliente_id)
        REFERENCES sac_clientes(id),

    CONSTRAINT chk_status CHECK (
        status IN ('ABERTO', 'EM_ANDAMENTO', 'RESOLVIDO', 'FECHADO')
    ),

    CONSTRAINT chk_prioridade CHECK (
        prioridade IN ('BAIXA', 'MEDIA', 'ALTA', 'CRITICA')
    )
);

-- ============================================================
-- Dados de exemplo (opcional — para testar sem a aplicação Java)
-- ============================================================

INSERT INTO sac_clientes (nome, email, cpf, telefone)
VALUES ('João Silva', 'joao@email.com', '111.222.333-44', '(11) 91111-2222');

INSERT INTO sac_clientes (nome, email, cpf, telefone)
VALUES ('Maria Santos', 'maria@email.com', '555.666.777-88', '(11) 93333-4444');

INSERT INTO sac_tickets (titulo, descricao, status, prioridade, cliente_id)
VALUES ('Produto não entregue', 'Pedido #98765 não foi entregue.', 'ABERTO', 'ALTA', 1);

INSERT INTO sac_tickets (titulo, descricao, status, prioridade, cliente_id)
VALUES ('Produto com defeito', 'Celular não liga.', 'EM_ANDAMENTO', 'CRITICA', 1);

INSERT INTO sac_tickets (titulo, descricao, status, prioridade, cliente_id)
VALUES ('Dúvida sobre devolução', 'Como devolver dentro do prazo?', 'FECHADO', 'BAIXA', 2);

COMMIT;
